name = "Robots? Where???"
author = "ning"
description = """
Where are the robots???
Someone told me there would be robots ðŸ˜­ðŸ˜­ðŸ˜­ðŸ˜­
Was I lied to?"""
category = "web"
difficulty = "easy"
points = 40
flag = "saint{I_FOUND_THE_ROBOTS!}"
